### ISSUE TITLE
Scroll to is not working on Firefox

### ISSUE THREAD

**Issue by andykras** [nash403/navscroll-js#1]
https://github.com/nash403/navscroll-js/blob/a93f0ef44ec623fc76aeaf8d8e97ea0ff9928a51/src/navscroll.js#L172

Hi nash403!

There should be 
`const clickedElement = e.currentTarget;`   
instead of
`const clickedElement = event.currentTarget;`

window.event is avalaible under Chrome\IE only.

**Comment by nash403** [comment]
Hello,

You are right ! I am fixing this right away.

Thank you !

**Comment by andykras** [comment]
Thanks!
