### ISSUE TITLE
Scrolling the page doesn't add active class to menu item

### ISSUE THREAD

**Issue by na86** [nash403/navscroll-js#4]
HiNash, tnx for the plugin, is amazing. 
I've go t a little issue with the page scrolling, in fact if i scroll the active class remain on the item i've clicked before. 

I'm using navscroll-js as a component in Vue.js 
this is my code
in the template
```
`<navscroll class="nav-scroll-items"
			container="html"
			item-selector=".item"
			:alwaysTrack="navscroll.alwaysTrack"
        	:cancelable="navscroll.cancelable"
        	:scrollAxis="navscroll.scrollAxis"
			:anchor="navscroll.anchor"
			active-class="active-element">
			<a 
			  v-for="(entry,i) of navscroll.entries" 
			  :key="i"
			  :href="'#'+entry.id+'-target'"
			  class="item"
			  :data-text="entry.name">
			  {{entry.name}}
			</a>
			<div class="navscroll-bg"></div>
	</navscroll>`
```

in data 

```
`navscroll: {
        anchor: false,
        alwaysTrack: false,
        cancelable: true,
        scrollAxis: 'y',
        el: 'section',
        entries: [{
          name: 'The dream',
          id: 'thedream'
        }, {
          name: 'Cars',
          id: 'cars'
        }, {
          name: 'Gallery',
          id: 'gallery'
        }, {
          name: '#zerouno',
          id: 'zerouno'
        }]
      },`
```

Thanks a lot for your answer
Cheers 

NND

**Comment by nash403** [comment]
Hello na86,

sorry for not responding to you earlier i got busy 😔

With the informations you gave me I can't see why your code wouldn't work.. Can you give me a complete copy/pastable example that reproduces the problem please ?

Take care !

**Comment by nash403** [comment]
I am closing for now, do not hesitate to post a comment when you have an example and I may re-open the issue 😉
