### ISSUE TITLE
SSR Support

### ISSUE THREAD

**Issue by davidbwaters** [nash403/navscroll-js#5]
Hi.  Could SSR support be added using something like vue-scrollto did [here](https://github.com/rigor789/vue-scrollto/commit/9bd66cacda4802b0290cca7d76e20f54418fb1b5)?

**Comment by nash403** [comment]
Hey, will do ASAP. thanks!

**Comment by nash403** [comment]
Can you please describe your problem ? The line of code you're showing me is already implemented in this package.

**Comment by davidbwaters** [comment]
Awesome.  I hadn't implemented it yet.  I'm new to Vue and from looking at the code was trying to determine if this was SSR friendly since it reference `vue-scrollto`, which worked without window.  Thanks, I'll try it out.  I did notice that it looks like this uses `mount`ng hooks, which [aren't called during SSR](https://vuejs.org/v2/api/#Options-Lifecycle-Hooks) (some hooks like`created` are called).

**Comment by nash403** [comment]
I haven't dug into SSR yet, so i can't tell. I'll take time to learn more about it later.
I'm closing the issue for now, if you have problems with `navscroll` & SSR do not hesitate to comment and describe the problem in detail or make a PR, i'll be happy to fix the issue.
